name: test

on:
   workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.0
    - name: Restore dependencies
      run: dotnet restore PowerThreadPool/PowerThreadPool.csproj
    - name: Build
      run: dotnet build PowerThreadPool/PowerThreadPool.csproj --no-restore
    - name: Run Tests and Generate TRX Report
      run: dotnet test UnitTest/UnitTest.csproj --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage"
    - name: Publish Unit Test Results
      uses: dorny/test-reporter@v1
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: 'Unit Test Results'
          reporter: 'dotnet-trx'
          path: '**/test-results.trx'
          fail_on_error: false
    - name: Install ReportGenerator tool
      run: dotnet tool install --global dotnet-reportgenerator-globaltool
    - name: Create reports
      run: reportgenerator "-reports:**/coverage.cobertura.xml" "-targetdir:coverage" -reporttypes:"HtmlInline_AzurePipelines;Cobertura"
   
